TOPLEVEL_LANG = verilog
SIM ?= verilator

THIS_DIR := $(dir $(abspath $(lastword $(MAKEFILE_LIST))))
ROOT := $(abspath $(THIS_DIR)/../..)

IMG_WIDTH ?= 5
IMG_HEIGHT ?= 4

export IMG_WIDTH
export IMG_HEIGHT

VERILOG_SOURCES = $(ROOT)/rtl/output_control.sv

TOPLEVEL = output_control
COCOTB_TEST_MODULES = test_output_control

COMPILE_ARGS += \
	-GIMG_WIDTH=$(IMG_WIDTH) \
	-GIMG_HEIGHT=$(IMG_HEIGHT)

export PYTHONPATH := $(ROOT):$(THIS_DIR):$(PYTHONPATH)

include $(shell cocotb-config --makefiles)/Makefile.sim
